services:
  api:
    build: ./api
    environment:
      - MONGOURL=mongodb://mongodb:27017/
    ports:
      - "8000:8000"
  vulnerability-cli:
    build: ./cli
    volumes:
      - ./files:/files
      - ./cli/logs:/cli/logs
    #profiles: ["cli-only"]
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./database:/data/db